//! *rsc2*
//!
//! A low level rust implementation of the Starcraft II protobuf api.
//!
//! The Starcraft II protobuf api was developed by blizzard in order
//! for no human agents to play and observe games. This crate provides an implementation of the
//! request/response scheme with the game. The purpose of this crate is provide the fullest api
//! to build an agent.
//!
//! The rust code generated by the protobuf translater can be quite verbose. The goal of this crate is not to provide simpler abstractions but to provide the ground work for
//! interacting with a running instance of Starcraft. In that objective it provides:
//!
//! * A runtime abstractions to interact with the game.
//! * A maintained rust version of the API with custom trait implementations.
//! * A RawApi which serves as a mid-level interface for building an agent.
//!
//! On a lower level:
//!
//! * The base for implementing custom hooks on a custom agent.
//! * A custom codec for encoding and decoding protobuf messages.
//!
//! # Example
//! A he
//! ```no_run
//! use rsc2::api::raw::{NewRawAgent, RawAgent, RawRequestGame};
//! use rsc2::hook::NextRequest;
//! use rsc2::pb::{api, prelude::*};
//!
//! struct HelloWorldSpamBot;
//!
//! impl RawAgent for HelloWorldSpamBot {
//!     fn on_response(&mut self, _: api::Response) -> NextRequest {
//!         let actions = vec![api::Action {
//!             action_raw: None,
//!             action_feature_layer: None,
//!             action_render: None,
//!             action_ui: None,
//!             action_chat: Some(api::ActionChat {
//!                 channel: Some(1),
//!                 message: Some("Hello World".into()),
//!             }),
//!             game_loop: None,
//!         }];
//!         NextRequest::Agent(api::request::Request::Action(api::RequestAction {
//!             actions,
//!         }))
//!     }
//! }
//!
//! #[rsc2::run]
//! fn main() -> std::io::Result<u32> {
//!     RawRequestGame::new(
//!         NewRawAgent(HelloWorldSpamBot {}),
//!         api::RequestCreateGame::default_config(), // default_config should be removed
//!         api::RequestJoinGame::default_config(),
//!     )
//! }
//!
//! ```

#![warn(
    missing_debug_implementations,
    missing_docs,
    rust_2018_idioms,
    unreachable_pub
)]

#[doc(inline)]
pub mod api;
#[doc(inline)]
pub mod hook;

#[doc(inline)]
pub mod runtime;

/// protobuf code and prelude traits
pub mod pb {
    #[doc(inline)]
    pub use rsc2_pb::api;
    #[doc(inline)]
    pub use rsc2_pb::prelude;
}

#[doc(inline)]
pub use rsc2_macro::run;
