use crate::api;

pub trait DefaultConfig {
    fn default_config() -> Self;
}

impl DefaultConfig for Vec<api::PlayerSetup> {
    fn default_config() -> Self {
        // Player vs Terran Easy Ai
        vec![
            api::PlayerSetup::player(),
            api::PlayerSetup::custom_bot(
                api::Race::Terran,
                api::Difficulty::Easy,
                api::AiBuild::RandomBuild,
            ),
        ]
    }
}

impl DefaultConfig for api::request_create_game::Map {
    fn default_config() -> Self {
        api::request_create_game::Map::LocalMap(api::LocalMap {
            map_path: Some("Ladder2017Season1/AbyssalReefLE.SC2Map".into()),
            map_data: None,
        })
    }
}

impl DefaultConfig for api::RequestCreateGame {
    fn default_config() -> Self {
        Self {
            /// Player vs Bot
            player_setup: Vec::default_config(),
            /// Fog is Enabled by Default
            disable_fog: Some(false),
            /// Seed is random see https://github.com/Blizzard/s2client-proto/blob/master/docs/protocol.md#randomness
            random_seed: None,
            /// Realtime mode by default
            realtime: Some(true),
            /// $SC2_PATH/StarCraftII/Maps/Ladder2017Season1/AbyssalReefLE.SC2Map
            map: Some(api::request_create_game::Map::default_config()),
        }
    }
}

impl DefaultConfig for api::InterfaceOptions {
    fn default_config() -> Self {
        Self::raw_mode()
    }
}

impl DefaultConfig for api::RequestJoinGame {
    fn default_config() -> Self {
        Self {
            participation: Some(api::request_join_game::Participation::Race(
                api::Race::Terran as i32,
            )),

            /// This is limited to what is specified in RequestCreateGame, but you can request less information if you want.
            options: Some(api::InterfaceOptions::default_config()),

            /// Do not set in the single-player case. This is the port a server will use.
            server_ports: None, /* Some(api::PortSet {game_port: Some(5000), base_port: Some(5000),}), */

            /// Do not set in the single-player case. These are the ports clients will use to initialize communication.
            client_ports: vec![], /* vec![api::PortSet {game_port: Some(5000), base_port: Some(5000),}], */

            /// deprecated
            shared_port: None,

            /// Use this to set the player's name to something other than autogenerated name.
            player_name: None,

            /// Both game creator and joiner should provide the ip address of the game creator in order to play remotely. Defaults to localhost.
            host_ip: None,
        }
    }
}
